### ISSUE TITLE
Doesn't work on Nuxt 3

### ISSUE THREAD

**Issue by jerryjappinen** [freddie-nelson/vue3-slider#23]
vue3-slider doesn't work on Nuxt 3. I guess it's the server not having access to `document` and this is then somehow not guarded against. It fails on the import though, and using `<ClientOnly>` doesn't help.

Repro: https://stackblitz.com/edit/vue3slider-on-nuxt?file=app.vue

Logs:

```
ReferenceError: document is not defined
    at addStyle (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:364:22)
    at addStylesToDom (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:348:20)
    at addStylesClient (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:302:3)
    at 5d0f (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:483:14)
    at __webpack_require__ (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:21:30)
    at Object.e503 (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:583:541)
    at __webpack_require__ (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:21:30)
    at Module.fb15 (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:1468:63)
    at __webpack_require__ (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:21:30)
    at eval (/home/projects/vue3slider-on-nuxt/node_modules/vue3-slider/dist/vue3-slider.common.js:85:18)
[nuxt] [request error] [unhandled] [500] [vite dev] Error loading external "vue3-slider".
  at async eval (./.nuxt/dev/index.mjs:117:22)  
  at async eval (./node_modules/h3/dist/index.mjs:571:19)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:517:7)
```

**Comment by trumpdo197** [comment]
@jerryjappinen It's the problem about how Nuxt handles Frontend-only libraries.

We need to conditionally load the FE-only library, Nuxt needs to check whether it's in Node.js environment or Browser environment before it actually loads/executes the library.

We could easily achieve that by lazy loading the slider component, something like this

![image](https://user-images.githubusercontent.com/25638210/197385189-e56e4c4e-a96e-4750-af05-555d42348fc7.png)

**Comment by TgMrP** [comment]
wrap it with 
<ClientOnly>

</ClientOnly>

**Comment by MusinRamil** [comment]
@jerryjappinen
It may not be relevant anymore, but it will be useful to other people.

For Nuxt 3

create client only component in `components/ui/slider/index.client.vue`
```
<template>
<vueSlider />
</template>

<script setup lang="ts">
const vueSlider = defineAsyncComponent(() => import('vue3-slider'));
</script>
```

and use component in you nuxt page or component 
```
<template>
<UiSlider />
</template>
```

If you need some props. You can always register and transfer them

**Comment by freddie-nelson** [comment]
Workaround posted 👍

**Comment by jerryjappinen** [comment]
@freddie-nelson it's still a problem of course since you would also want to render the slider on the server. But maybe a different ticket.
